/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas:           '#f9f6f1',
        'surface-card':   '#ffffff',
        'surface-soft':   '#f2ede4',
        'surface-strong': '#e8e2d6',
        hairline:         '#e0d8cc',
        'hairline-soft':  '#ece7dd',
        cobalt:           '#5058f0',
        sage:             '#70b080',
        teal:             '#90c0c0',
        peach:            '#ffb084',
        lavender:         '#c0c0f0',
        ochre:            '#e8b94a',
        coral:            '#e85d4a',
        ink:              '#1a1a1a',
        body:             '#3a3a3a',
        muted:            '#6a6a6a',
        'muted-soft':     '#9a9a9a',
      },
      borderRadius: {
        xs:   '6px',
        sm:   '8px',
        md:   '12px',
        lg:   '16px',
        xl:   '24px',
        pill: '9999px',
      },
      fontFamily: {
        kedu:   ['"KERIS-KEDU"', 'sans-serif'],
        myeong: ['"Nanum-Myeongjo"', 'serif'],
        jalnan: ['"Jalnan"', 'sans-serif'],
      },
      spacing: {
        xxs:     '4px',
        xs:      '8px',
        sm:      '12px',
        md:      '16px',
        lg:      '24px',
        xl:      '32px',
        xxl:     '48px',
        section: '80px',
      },
    },
  },
  plugins: [],
};
