SAMPLE_FOOD_DATA = [
    {"food_name": "흰쌀밥", "food_name_en": "steamed_rice", "calories": 130.0, "carbs": 28.1, "protein": 2.5, "fat": 0.3, "serving_size": 200.0, "category": "밥류", "is_korean": True},
    {"food_name": "제육볶음", "food_name_en": "stir_fried_pork", "calories": 260.0, "carbs": 10.0, "protein": 16.0, "fat": 15.0, "serving_size": 200.0, "category": "육류", "is_korean": True},
    {"food_name": "된장국", "food_name_en": "soybean_paste_soup", "calories": 60.0, "carbs": 5.0, "protein": 4.0, "fat": 2.5, "serving_size": 200.0, "category": "국/찌개", "is_korean": True},
    {"food_name": "김치", "food_name_en": "kimchi", "calories": 15.0, "carbs": 2.5, "protein": 1.0, "fat": 0.0, "serving_size": 100.0, "category": "김치류", "is_korean": True},
    {"food_name": "치킨", "food_name_en": "fried_chicken", "calories": 290.0, "carbs": 15.0, "protein": 22.0, "fat": 16.0, "serving_size": 150.0, "category": "튀김류", "is_korean": True},
    {"food_name": "피자 1조각", "food_name_en": "pizza", "calories": 270.0, "carbs": 33.0, "protein": 12.0, "fat": 10.0, "serving_size": 100.0, "category": "패스트푸드", "is_korean": False},
    {"food_name": "샐러드", "food_name_en": "salad", "calories": 80.0, "carbs": 8.0, "protein": 3.0, "fat": 4.0, "serving_size": 150.0, "category": "채소류", "is_korean": False},
    {"food_name": "라면", "food_name_en": "ramen", "calories": 500.0, "carbs": 75.0, "protein": 10.0, "fat": 18.0, "serving_size": 500.0, "category": "면류", "is_korean": True},
    {"food_name": "삼겹살", "food_name_en": "pork_belly", "calories": 400.0, "carbs": 0.0, "protein": 15.0, "fat": 38.0, "serving_size": 150.0, "category": "육류", "is_korean": True},
    {"food_name": "비빔밥", "food_name_en": "bibimbap", "calories": 570.0, "carbs": 90.0, "protein": 20.0, "fat": 15.0, "serving_size": 400.0, "category": "밥류", "is_korean": True},
    {"food_name": "떡볶이", "food_name_en": "tteokbokki", "calories": 350.0, "carbs": 70.0, "protein": 8.0, "fat": 4.0, "serving_size": 300.0, "category": "분식", "is_korean": True},
    {"food_name": "불고기", "food_name_en": "bulgogi", "calories": 220.0, "carbs": 15.0, "protein": 20.0, "fat": 8.0, "serving_size": 150.0, "category": "육류", "is_korean": True},
    {"food_name": "파스타", "food_name_en": "pasta", "calories": 430.0, "carbs": 65.0, "protein": 14.0, "fat": 13.0, "serving_size": 300.0, "category": "면류", "is_korean": False},
    {"food_name": "햄버거", "food_name_en": "hamburger", "calories": 450.0, "carbs": 40.0, "protein": 25.0, "fat": 20.0, "serving_size": 200.0, "category": "패스트푸드", "is_korean": False},
    {"food_name": "바나나", "food_name_en": "banana", "calories": 89.0, "carbs": 23.0, "protein": 1.1, "fat": 0.3, "serving_size": 120.0, "category": "과일", "is_korean": False},
    {"food_name": "계란 1개", "food_name_en": "egg", "calories": 70.0, "carbs": 0.6, "protein": 6.0, "fat": 5.0, "serving_size": 60.0, "category": "달걀/유제품", "is_korean": False},
    {"food_name": "두부", "food_name_en": "tofu", "calories": 76.0, "carbs": 1.9, "protein": 8.0, "fat": 4.0, "serving_size": 100.0, "category": "콩류", "is_korean": True},
    {"food_name": "고등어 구이", "food_name_en": "grilled_mackerel", "calories": 280.0, "carbs": 0.0, "protein": 25.0, "fat": 18.0, "serving_size": 150.0, "category": "생선류", "is_korean": True},
    {"food_name": "오트밀", "food_name_en": "oatmeal", "calories": 150.0, "carbs": 27.0, "protein": 5.0, "fat": 2.5, "serving_size": 100.0, "category": "시리얼", "is_korean": False},
    {"food_name": "아메리카노", "food_name_en": "americano", "calories": 10.0, "carbs": 2.0, "protein": 0.3, "fat": 0.0, "serving_size": 400.0, "category": "음료", "is_korean": False},
]
